### ISSUE TITLE
Potential fail in teardown

### ISSUE THREAD

**Issue by AssafMiron** [infamousjoeg/workshop-orchestration#5]
https://github.com/infamousjoeg/workshop-orchestration/blob/d3dcc8ba1444591fddfb72ae80e6c8d7b77ac097/teardown.ps1#L29

If you removed the safe already, you cannot remove the safe owner anymore (since the safe does not exist)
I think you can remove this line entirely, you already deleted the user from AD and deleted the safe
The user cannot login and the safe does not exist

By the way, when creating the safe, create it with object history equals to 0 so you can delete it instantly and not wait the default 7 days of object retention

**Comment by infamousjoeg** [comment]
OMG!  This is exactly what I needed!  I didn't know I could set it to `0` and so was setting it to `1`.

Then, I'd attempt to remove the Safe (despite knowing it wouldn't delete) so that the accounts within would be marked for deletion.  That's why I was also removing the Safe Member, just in case the safe failed to remove.

You're right, though... if the AD User is removed, whether the safe member persists or not doesn't matter anymore.
